import type { Metadata } from 'next'
import './globals.css'
import { Josefin_Sans } from 'next/font/google'

import Providers from '@/providers/query-provider'

export const josefin = Josefin_Sans({
  subsets: ['latin'],
  display: 'swap',
})

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
